# required properties
group = com.almostreliable
modId = merequester
modName = ME Requester
modVersion = 1.5.1
minecraftVersion = 26.1.2
neoforgeVersion = 26.1.2.81

# replacement properties
modAuthor = Almost Reliable
modDescription = Keep resources in your ME-System in stock.
license = GNU Lesser General Public License v3.0
githubUser = AlmostReliable
githubRepo = merequester

# mod dependencies
aeVersion = 26.1.10-beta
wtlibVersion = 26.1.1-beta

# settings
almostgradle.buildconfig = ModConstants
almostgradle.launchArgs.autoWorldJoin = true
almostgradle.recipeViewers.jei.runConfig = true
almostgradle.recipeViewers.jei.version = 29.21.0.66

# gradle
org.gradle.vfs.watch = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
