# required properties
group = com.almostreliable
modId = merequester
modName = ME Requester
modVersion = 1.5.0
minecraftVersion = 1.21.1
neoforgeVersion = 21.1.169

# replacement properties
modAuthor = Almost Reliable
modDescription = Keep resources in your ME-System in stock.
license = GNU Lesser General Public License v3.0
githubUser = AlmostReliable
githubRepo = merequester

# mod dependencies
aeVersion = 19.2.13
wtlibVersion = 19.2.5

# settings
neoForge.parchment.minecraftVersion = 1.21.1
neoForge.parchment.mappingsVersion = 2024.11.17
almostgradle.buildconfig.name = ModConstants
almostgradle.launchArgs.autoWorldJoin = true
almostgradle.recipeViewers.emi.runConfig = true
almostgradle.recipeViewers.emi.version = 1.1.21
almostgradle.recipeViewers.emi.minecraftVersion = 1.21.1

# gradle
org.gradle.vfs.watch = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
