modLoader = "javafml"
loaderVersion = "[${forgeLoaderVersion},)"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"
logoFile = "logo.png"

[[mixins]]
config="merequester.mixins.json"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''${modDescription}'''

[[dependencies.${modId}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "ae2"
type = "REQUIRED"
versionRange = "[${aeVersion},)"
ordering = "AFTER"
side = "BOTH"
