@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.merequester.client.abstraction;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
