@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.merequester.mixin.registration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
