@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.merequester.wireless.ae2wtlib;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
