@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.merequester.platform;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
